# ROOT:
#   - NETOPS
#   - PROD:
#       - US-EAST-1:
#           - ACTIVE
#           - PASSIVE
#       - US-EAST-2:
#           - ACTIVE
#           - PASSIVE
#       - US-WEST-2:
#           - ACTIVE
#           - PASSIVE
#       - EU-EAST-2:
#           - ACTIVE
#           - PASSIVE
#   - QA:
#       - QA1
#       - QA2
#   - DEV:
#       - DEV1
#       - DEV2
#       - DEV3
#       - DEV4
#   - PERSONAL:
#       - PLATFORM
#       - DATA
#       - MOBILE
#   - DEVOPS

ROOT:
  - ONE
  - TWO
  - THREE
  - FOUR
