name: documentation

on:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - main
    workflow_dispatch:

defaults:
    run:
        working-directory: ./website

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: website
          git-user: baremetalhelp
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
